server:
  port: ${PORT:8080} #服务端口
  servlet:
    context-path: /authorization
spring:
  application:
    name: IPCDP-OPEN-SERVER-AUTHORIZATION
  redis:
    # 你 Redis 主机地址
    host: localhost
    # 你 Redis 主机端口
    port: 6379
    # 我们使用 Lettuce 客户端，比 Jedis 更高效
    lettuce:
      # 连接池配置
      pool:
        # 连接池中的最小空闲连接，默认 0
        min-idle: 0
        # 连接池中的最大空闲连接，默认 8
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制），默认 -1ms
        max-wait: -1ms
        # 连接池最大连接数（使用负值表示没有限制），默认 8
        max-active: 8
