eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:50101/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    home-page-url-path: ${server.servlet.context-path}
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.int(100)}
    leaseRenewalIntervalInSeconds: 10
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms